"""changes in the parking slots table 

Revision ID: 945f1433c591
Revises: 0805e9955026
Create Date: 2026-02-18 16:43:58.372706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945f1433c591'
down_revision: Union[str, Sequence[str], None] = '0805e9955026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_parking_slots_parking_lot_id'), 'parking_slots', ['parking_lot_id'], unique=False)
    op.create_unique_constraint('uq_parking_lot_slot_number', 'parking_slots', ['parking_lot_id', 'slot_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_parking_lot_slot_number', 'parking_slots', type_='unique')
    op.drop_index(op.f('ix_parking_slots_parking_lot_id'), table_name='parking_slots')
    # ### end Alembic commands ###
