"""changes in parkinglots

Revision ID: eff232935f93
Revises: 83ed1af573c1
Create Date: 2026-02-17 12:03:29.035129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff232935f93'
down_revision: Union[str, Sequence[str], None] = '83ed1af573c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_lots', sa.Column('available_slots', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('parking_lots', 'available_slots')
    # ### end Alembic commands ###
